export const SOCIALS = {
  x: "https://x.com/myMemeArcade",
  telegram: "https://t.me/memearcade",
  stake: "https://staking.memearcade",
};

export const GAMES = [
  {
    id: "allstars",
    num: "01",
    title: "BundleCat All Stars",
    displayLines: ["ALL", "STARS"],
    category: "Tournament Crypto Game",
    mode: "SOLO / SQUAD",
    tagline: "Cats vs legends. Winner takes the pot.",
    description:
      "All Star Cats hold off the NBA All Stars in a high-stakes arena showdown. Climb the ladder, out-play the legends, and cash the whole pot out in your own $BUN memecoin.",
    chips: ["SEASON LADDER", "PLAY IN $BUN", "LOW RISK / HIGH REWARD", "LIVE PAYOUTS"],
    ticker: "$BUN",
    community: "Robinhood",
    href: "https://allstars.memearcade.my",
    image: "/images/allstars.webp",
    theme: "#F4B223",
    themeSoft: "rgba(244,178,35,0.16)",
    activeNow: "48,290",
  },
  {
    id: "feferdream",
    num: "02",
    title: "Feferdream Apocalypse",
    displayLines: ["FEFERDREAM", "APOCALYPSE"],
    category: "Survival Dreamscape",
    mode: "SOLO / SQUAD",
    tagline: "Dream hard. Survive harder.",
    description:
      "Dino hunters take on Dragons to stop the apocalypse. Reality is melting and only the sharpest survive the dream — run the wasteland, stack rewards, and cash out in your own $fefer memecoin before the sky falls.",
    chips: ["SURVIVAL RUNS", "PLAY IN $FEFER", "LOW RISK / HIGH REWARD", "SQUAD EVENTS"],
    ticker: "$FEFER",
    community: "Stable",
    href: "https://feferdream.memearcade.my",
    image: "/images/feferdream.webp",
    theme: "#FF3B30",
    themeSoft: "rgba(255,59,48,0.16)",
    activeNow: "64,318",
  },
  {
    id: "cashcats",
    num: "03",
    title: "Cash Cats 'n' Money Mice",
    displayLines: ["CASH", "CATS 'N'", "MONEY", "MICE"],
    category: "Heist Crypto Game",
    mode: "SOLO / SQUAD",
    tagline: "Street cats. Suited mice. One pot.",
    description:
      "Street-cat crews versus suited mouse syndicates in a neon-soaked heist for the pot. Outsmart the mafia, grab the loot, and cash out in your own $cashcat memecoin — running now.",
    chips: ["HEIST RUNS", "PLAY IN $CASHCAT", "LOW RISK / HIGH REWARD", "CREW BATTLES"],
    ticker: "$CASHCAT",
    community: "Robinhood",
    href: "https://cashcats.memearcade.my",
    image: "/images/cashcats.webp",
    theme: "#22C55E",
    themeSoft: "rgba(34,197,94,0.16)",
    activeNow: "39,774",
  },
];
